fix(bashrc) promt-look

diff --git a/machines/Workstation/bashrc b/machines/Workstation/bashrc
--- a/machines/Workstation/bashrc
+++ b/machines/Workstation/bashrc
@@ -43,37 +43,54 @@ case "$TERM" in
     xterm-color|*-256color) color_prompt=yes;;
 esac
 
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-#force_color_prompt=yes
 
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-	# We have color support; assume it's compliant with Ecma-48
-	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-	# a case would tend to support setf rather than setaf.)
-	color_prompt=yes
+
+# Function: Trim path to max 16 chars (shows last 2 segments if long)
+get_trimmed_path() {
+    local p="${PWD/#$HOME/~}"
+    if [ ${#p} -gt 16 ]; then
+        # Grab last 2 directory segments (e.g., ...share/chezmoi)
+        echo "...$(echo "$p" | rev | cut -d'/' -f1,2 | rev)" | cut -c1-16
     else
-	color_prompt=
+        echo "$p"
     fi
-fi
+}
 
-if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
-else
-    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
-fi
-unset color_prompt force_color_prompt
+# Function: Get Git Branch and Status
+get_git_info() {
+    if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
+        local branch=$(git branch --show-current)
+        local status=$(git status --porcelain | wc -l)
+        local icon="✔"
+        # If there are changes, show count and ✗
+        [ "$status" -ne 0 ] && icon="✗:$status"
+        echo " [ $branch $icon ]"
+    fi
+}
 
-# If this is an xterm set the title to user@host:dir
-case "$TERM" in
-xterm*|rxvt*)
-   # PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    ;;
-*)
-    ;;
-esac
+# The Main Prompt Function
+prompt_command() {
+    local EXIT="$?"
+    local SYMBOL="❯"
+    
+    # Color coding
+    local G="\[\e[1;32m\]" # Green (User@Host)
+    local B="\[\e[1;34m\]" # Blue (Path)
+    local Y="\[\e[1;33m\]" # Yellow (Git)
+    local P="\[\e[1;35m\]" # Purple (Arrow)
+    local R="\[\e[1;31m\]" # Red (Error)
+    local W="\[\e[0m\]"    # White/Reset
+
+    # Turn arrow red if last command failed
+    [ $EXIT != 0 ] && SYMBOL="$R$SYMBOL" || SYMBOL="$P$SYMBOL"
+
+    # Line 1: user@host:path [git branch status]
+    # Line 2: The Input Arrow
+    PS1="\n$G\u@\h$W:$B\$(get_trimmed_path)$Y\$(get_git_info)$W\n$SYMBOL $W"
+}
+
+# Set the prompt
+PROMPT_COMMAND=prompt_command
 
 
 # Alias definitions.
